workflows:
    version: 2
    build:
        jobs:
            - build
            - lint:
                requires:
                    - build
            - package:
                requires:
                    - build
                    - lint
                filters:
                    branches:
                        only: master

default-job: &default-job
    working_directory: ~/src

node-job: &node-job
    <<: *default-job
    docker:
        - image: node

&attach_workspace = attach_workspace:
    - attach_workspace:
        at: ~/

jobs:
    build:
        <<: *node-job
        steps:
            - checkout
            - restore_cache:
                keys:
                    - dependencies-{{ checksum "package-lock.json" }}
                    - dependencies-
            - run:
                name: Install packages
                command: npm install
            - save_cache:
                paths:
                    - node_modules
                key: dependencies-{{ checksum "package-lock.json" }}
            - run:
                name: Build
                command: node_modules/.bin/scri build-only
            - persist_to_workspace:
                root: ~/
                paths:
                    - src

    lint:
        <<: *node-job
        steps:
            - *attach_workspace
            - run:
                name: Package extension
                command: node_modules/.bin/scri lint-only

    package:
        <<: *node-job
        steps:
            - *attach_workspace
            - run:
                name: Package extension
                command: node_modules/.bin/scri package-only
